#!/bin/python

'''
Description : The original h5 file generated by Lepton Injector does not store
    the pdg code of the primary particle properly (in the 'initial' object).
    This script fixes the pdg code issue by updating the already generated h5
    file.
'''

import h5py as h5
from optparse import OptionParser

parser = OptionParser()
parser.add_option('-f', '--Filename', dest='FILE', type=str)

(option, args) = parser.parse_args()

fname = option.FILE

hf = h5.File(fname,"a")

hf['RangedInjector0']['initial']['ParticleType'] = hf['RangedInjector0']['properties']['initialType']

hf.close()
print ("Primary particle type fixed!")
